# Generated by Django 4.2 on 2024-08-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realapp", "0004_bestrecord15_bestrecord60_pastrecords_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastrecords",
            old_name="time",
            new_name="time_typing",
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
