# Generated by Django 4.2 on 2024-08-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realapp", "0005_rename_time_pastrecords_time_typing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastrecords",
            name="time_typing",
            field=models.IntegerField(default=15),
        ),
    ]
