# Generated by Django 4.2 on 2024-08-03 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realapp", "0006_alter_pastrecords_time_typing"),
    ]

    operations = [
        migrations.DeleteModel(
            name="bestRecord15",
        ),
        migrations.DeleteModel(
            name="bestRecord60",
        ),
    ]
