# Generated by Django 4.2 on 2025-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realapp", "0007_delete_bestrecord15_delete_bestrecord60"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_pic",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
